package com.EiriniManu.Messaging;

public enum MessageTag {
        IMPLEMENTINGCLASS,
        ADDCALLINGCLASS,
        REMOVECALLINGCLASS,
        CLASSMETHODNAME,
        CLASSMETHODRETURNTYPE,
        CLASSFIELDNAME,
        CLASSFIELDTYPE,
        METHODNAME,
        METHODRETURNTYPE,
        PARAMETERTYPE,
        PARAMETERNAME,
        CATCHPARAMETERTYPE,
        CATCHPARAMETERNAME,
        METHODCALL,
        METHODCALLNODE,
        METHODCALLTARGET,
        VARIABLEDECLARATIONNAME,
        VARIABLEDECLARATIONTYPE,
        BLOCKNODE,
        METHODBLOCK,
        ADDMETHODCALLER,
        REMOVEMETHODCALLER,
        RESET
}
