package com.EiriniManu.Messaging;

public enum MessageTag {
        IMPLEMENTINGCLASS,
        CALLINGCLASS,
        CLASSMETHODNAME,
        CLASSMETHODRETURNTYPE,
        CLASSFIELDNAME,
        CLASSFIELDTYPE,
        METHODNAME,
        METHODRETURNTYPE,
        PARAMETERTYPE,
        PARAMETERNAME,
        CATCHPARAMETERTYPE,
        CATCHPARAMETERNAME,
        METHODCALL,
        METHODCALLNODE,
        METHODCALLTARGET,
        VARIABLEDECLARATIONNAME,
        VARIABLEDECLARATIONTYPE,
        BLOCKNODE,
        METHODBLOCK,
        METHODCALLER,
        RESET
}
